// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setupProfileGraphs(lv_event_t * e);
void setRunChart(lv_event_t * e);
void setProfileNumber(lv_event_t * e);
void setSelectedMode(lv_event_t * e);
void KeyboardDone(lv_event_t * e);
void runButtonTriggered(lv_event_t * e);
void StopButtonTriggered(lv_event_t * e);
void runManualButtonTriggered(lv_event_t * e);
void SetRpmSlider(lv_event_t * e);
void minus50RPM(lv_event_t * e);
void add50RPM(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
