// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManualRunScreenPanel = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_ManualRunScreenPanel, 480);
    lv_obj_set_height(ui_ManualRunScreenPanel, 320);
    lv_obj_set_align(ui_ManualRunScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ManualRunScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualRunScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualRunScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualPanelTop = lv_obj_create(ui_ManualRunScreenPanel);
    lv_obj_set_width(ui_ManualPanelTop, 200);
    lv_obj_set_height(ui_ManualPanelTop, 40);
    lv_obj_set_x(ui_ManualPanelTop, 0);
    lv_obj_set_y(ui_ManualPanelTop, -22);
    lv_obj_set_align(ui_ManualPanelTop, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ManualPanelTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ManualPanelTop, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManualPanelTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualRunLabel = lv_label_create(ui_ManualPanelTop);
    lv_obj_set_width(ui_ManualRunLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualRunLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ManualRunLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualRunLabel, "Manual Run Motor");
    lv_obj_set_style_text_color(ui_ManualRunLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualRunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ManualRunLabel, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuPanel3 = lv_obj_create(ui_ManualRunScreenPanel);
    lv_obj_set_width(ui_ToMainMenuPanel3, 98);
    lv_obj_set_height(ui_ToMainMenuPanel3, 40);
    lv_obj_set_x(ui_ToMainMenuPanel3, -186);
    lv_obj_set_y(ui_ToMainMenuPanel3, -23);
    lv_obj_set_align(ui_ToMainMenuPanel3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ToMainMenuPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ToMainMenuPanel3, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToMainMenuPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuLabel3 = lv_label_create(ui_ToMainMenuPanel3);
    lv_obj_set_width(ui_ToMainMenuLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToMainMenuLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToMainMenuLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToMainMenuLabel3, "< Main");
    lv_obj_set_style_text_color(ui_ToMainMenuLabel3, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToMainMenuLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToMainMenuLabel3, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedPanel1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_SpeedPanel1, 120);
    lv_obj_set_height(ui_SpeedPanel1, 120);
    lv_obj_set_x(ui_SpeedPanel1, -132);
    lv_obj_set_y(ui_SpeedPanel1, -32);
    lv_obj_set_align(ui_SpeedPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SpeedPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGSpeed1 = lv_img_create(ui_SpeedPanel1);
    lv_img_set_src(ui_BGSpeed1, &ui_img_942215904);
    lv_obj_set_width(ui_BGSpeed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BGSpeed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BGSpeed1, -1);
    lv_obj_set_y(ui_BGSpeed1, 1);
    lv_obj_set_align(ui_BGSpeed1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSpeed1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSpeed1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BGSpeed1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BGSpeed1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BGSpeed1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BGSpeed1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Needle1 = lv_img_create(ui_SpeedPanel1);
    lv_img_set_src(ui_Needle1, &ui_img_1601502596);
    lv_obj_set_width(ui_Needle1, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Needle1, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Needle1, -1);
    lv_obj_set_y(ui_Needle1, 35);
    lv_obj_set_align(ui_Needle1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle1, 3, -13);

    ui_Arc2 = lv_arc_create(ui_SpeedPanel1);
    lv_obj_set_width(ui_Arc2, 115);
    lv_obj_set_height(ui_Arc2, 115);
    lv_obj_set_x(ui_Arc2, -1);
    lv_obj_set_y(ui_Arc2, 1);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Arc2, 0, 2800);
    lv_arc_set_value(ui_Arc2, 0);
    lv_arc_set_bg_angles(ui_Arc2, 90, 340);
    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Arc2, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc2, &ui_img_1798728470, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_StartManualButton = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_StartManualButton, 100);
    lv_obj_set_height(ui_StartManualButton, 50);
    lv_obj_set_x(ui_StartManualButton, -183);
    lv_obj_set_y(ui_StartManualButton, 127);
    lv_obj_set_align(ui_StartManualButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartManualButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartManualButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartManualButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartManualButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartManualButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartManualButton, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartManualButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartManualButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunLabel1 = lv_label_create(ui_StartManualButton);
    lv_obj_set_width(ui_RunLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunLabel1, "Run");
    lv_obj_set_style_text_color(ui_RunLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunLabel1, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RunLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RunLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton1 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_StopButton1, 100);
    lv_obj_set_height(ui_StopButton1, 50);
    lv_obj_set_x(ui_StopButton1, -80);
    lv_obj_set_y(ui_StopButton1, 128);
    lv_obj_set_align(ui_StopButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopButton1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopButton1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StopButton1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StopButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StopButton1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLabel1 = lv_label_create(ui_StopButton1);
    lv_obj_set_width(ui_StopLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLabel1, "E-Stop");
    lv_obj_set_style_text_color(ui_StopLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopLabel1, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StopLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StopLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMPanel1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_RPMPanel1, 100);
    lv_obj_set_height(ui_RPMPanel1, 50);
    lv_obj_set_x(ui_RPMPanel1, -132);
    lv_obj_set_y(ui_RPMPanel1, 61);
    lv_obj_set_align(ui_RPMPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_RPMPanel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPMPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_RPMPanel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 29);
    lv_obj_set_y(ui_Label1, 13);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Rpm");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x80FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMLabel11 = lv_label_create(ui_RPMPanel1);
    lv_obj_set_width(ui_RPMLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLabel11, -8);
    lv_obj_set_y(ui_RPMLabel11, -19);
    lv_label_set_text(ui_RPMLabel11, "0000");
    lv_obj_set_style_text_color(ui_RPMLabel11, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMLabel11, &ui_font_Font_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmKnob = lv_arc_create(ui_Screen5);
    lv_obj_set_width(ui_RpmKnob, 120);
    lv_obj_set_height(ui_RpmKnob, 120);
    lv_obj_set_x(ui_RpmKnob, 93);
    lv_obj_set_y(ui_RpmKnob, -31);
    lv_obj_set_align(ui_RpmKnob, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RpmKnob, 0, 2800);
    lv_arc_set_value(ui_RpmKnob, 0);


    ui_ManualMinRPM = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_ManualMinRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualMinRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualMinRPM, -2);
    lv_obj_set_y(ui_ManualMinRPM, 4);
    lv_obj_set_align(ui_ManualMinRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualMinRPM, "0 Rpm");
    lv_obj_set_style_text_color(ui_ManualMinRPM, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualMinRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ManualMinRPM, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualMaxRPM = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_ManualMaxRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualMaxRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualMaxRPM, 192);
    lv_obj_set_y(ui_ManualMaxRPM, 6);
    lv_obj_set_align(ui_ManualMaxRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualMaxRPM, "2800 RPM");
    lv_obj_set_style_text_color(ui_ManualMaxRPM, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualMaxRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ManualMaxRPM, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualRPMLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_ManualRPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualRPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualRPMLabel, 94);
    lv_obj_set_y(ui_ManualRPMLabel, -31);
    lv_obj_set_align(ui_ManualRPMLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualRPMLabel, "0000");
    lv_obj_set_style_text_color(ui_ManualRPMLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualRPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ManualRPMLabel, &ui_font_Font_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minus50Button = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_minus50Button, 100);
    lv_obj_set_height(ui_minus50Button, 50);
    lv_obj_set_x(ui_minus50Button, 37);
    lv_obj_set_y(ui_minus50Button, 59);
    lv_obj_set_align(ui_minus50Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minus50Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minus50Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_minus50Button, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minus50Button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minus50Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_minus50Button, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_minus50Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_minus50Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minus50Label = lv_label_create(ui_minus50Button);
    lv_obj_set_width(ui_minus50Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minus50Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_minus50Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minus50Label, "-50 Rpm");
    lv_obj_set_style_text_color(ui_minus50Label, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minus50Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minus50Label, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_minus50Label, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_minus50Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plus50Button = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_plus50Button, 100);
    lv_obj_set_height(ui_plus50Button, 50);
    lv_obj_set_x(ui_plus50Button, 154);
    lv_obj_set_y(ui_plus50Button, 58);
    lv_obj_set_align(ui_plus50Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_plus50Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_plus50Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_plus50Button, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_plus50Button, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plus50Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_plus50Button, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_plus50Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_plus50Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plus50Label = lv_label_create(ui_plus50Button);
    lv_obj_set_width(ui_plus50Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plus50Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_plus50Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plus50Label, "+50 Rpm");
    lv_obj_set_style_text_color(ui_plus50Label, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plus50Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_plus50Label, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_plus50Label, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_plus50Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner4 = lv_spinner_create(ui_Screen5, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 40);
    lv_obj_set_height(ui_Spinner4, 40);
    lv_obj_set_x(ui_Spinner4, -4);
    lv_obj_set_y(ui_Spinner4, 127);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ToMainMenuPanel3, ui_event_ToMainMenuPanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartManualButton, ui_event_StartManualButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton1, ui_event_StopButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RpmKnob, ui_event_RpmKnob, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minus50Button, ui_event_minus50Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plus50Button, ui_event_plus50Button, LV_EVENT_ALL, NULL);

}
