// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreenPanel1 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_SettingScreenPanel1, 480);
    lv_obj_set_height(ui_SettingScreenPanel1, 320);
    lv_obj_set_align(ui_SettingScreenPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreenPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreenPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreenPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanelStart = lv_obj_create(ui_SettingScreenPanel1);
    lv_obj_set_width(ui_TopPanelStart, 200);
    lv_obj_set_height(ui_TopPanelStart, 40);
    lv_obj_set_x(ui_TopPanelStart, 0);
    lv_obj_set_y(ui_TopPanelStart, -22);
    lv_obj_set_align(ui_TopPanelStart, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopPanelStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TopPanelStart, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopPanelStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanelStartLabel = lv_label_create(ui_TopPanelStart);
    lv_obj_set_width(ui_TopPanelStartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TopPanelStartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TopPanelStartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TopPanelStartLabel, "Run Motor");
    lv_obj_set_style_text_color(ui_TopPanelStartLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TopPanelStartLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TopPanelStartLabel, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuPanel1 = lv_obj_create(ui_SettingScreenPanel1);
    lv_obj_set_width(ui_ToMainMenuPanel1, 98);
    lv_obj_set_height(ui_ToMainMenuPanel1, 40);
    lv_obj_set_x(ui_ToMainMenuPanel1, -186);
    lv_obj_set_y(ui_ToMainMenuPanel1, -23);
    lv_obj_set_align(ui_ToMainMenuPanel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ToMainMenuPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ToMainMenuPanel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToMainMenuPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuLabel1 = lv_label_create(ui_ToMainMenuPanel1);
    lv_obj_set_width(ui_ToMainMenuLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToMainMenuLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToMainMenuLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToMainMenuLabel1, "< Main");
    lv_obj_set_style_text_color(ui_ToMainMenuLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToMainMenuLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToMainMenuLabel1, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuPanel2 = lv_obj_create(ui_SettingScreenPanel1);
    lv_obj_set_width(ui_ToMainMenuPanel2, 98);
    lv_obj_set_height(ui_ToMainMenuPanel2, 40);
    lv_obj_set_x(ui_ToMainMenuPanel2, 182);
    lv_obj_set_y(ui_ToMainMenuPanel2, -22);
    lv_obj_set_align(ui_ToMainMenuPanel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ToMainMenuPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ToMainMenuPanel2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToMainMenuPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuLabel2 = lv_label_create(ui_ToMainMenuPanel2);
    lv_obj_set_width(ui_ToMainMenuLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToMainMenuLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToMainMenuLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToMainMenuLabel2, "Manual >");
    lv_obj_set_style_text_color(ui_ToMainMenuLabel2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToMainMenuLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToMainMenuLabel2, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningProfilePanel = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_RunningProfilePanel, 344);
    lv_obj_set_height(ui_RunningProfilePanel, 185);
    lv_obj_set_x(ui_RunningProfilePanel, 60);
    lv_obj_set_y(ui_RunningProfilePanel, -25);
    lv_obj_set_align(ui_RunningProfilePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RunningProfilePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningProfile = lv_chart_create(ui_RunningProfilePanel);
    lv_obj_set_width(ui_RunningProfile, 295);
    lv_obj_set_height(ui_RunningProfile, 152);
    lv_obj_set_x(ui_RunningProfile, 19);
    lv_obj_set_y(ui_RunningProfile, -11);
    lv_obj_set_align(ui_RunningProfile, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_RunningProfile, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_RunningProfile, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_RunningProfile, LV_CHART_TYPE_SCATTER);
    lv_chart_set_point_count(ui_RunningProfile, 200);
    lv_chart_set_range(ui_RunningProfile, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_RunningProfile, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_RunningProfile, 10, 10);
    lv_chart_set_axis_tick(ui_RunningProfile, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_RunningProfile, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_RunningProfile, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_SpeedPanel = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_SpeedPanel, 120);
    lv_obj_set_height(ui_SpeedPanel, 120);
    lv_obj_set_x(ui_SpeedPanel, -174);
    lv_obj_set_y(ui_SpeedPanel, -56);
    lv_obj_set_align(ui_SpeedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BGSpeed = lv_img_create(ui_SpeedPanel);
    lv_img_set_src(ui_BGSpeed, &ui_img_942215904);
    lv_obj_set_width(ui_BGSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BGSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BGSpeed, -1);
    lv_obj_set_y(ui_BGSpeed, 1);
    lv_obj_set_align(ui_BGSpeed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BGSpeed, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BGSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Needle = lv_img_create(ui_SpeedPanel);
    lv_img_set_src(ui_Needle, &ui_img_1601502596);
    lv_obj_set_width(ui_Needle, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Needle, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Needle, -1);
    lv_obj_set_y(ui_Needle, 35);
    lv_obj_set_align(ui_Needle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Needle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Needle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Needle, 3, -13);

    ui_RedArc = lv_arc_create(ui_SpeedPanel);
    lv_obj_set_width(ui_RedArc, 115);
    lv_obj_set_height(ui_RedArc, 115);
    lv_obj_set_x(ui_RedArc, -1);
    lv_obj_set_y(ui_RedArc, 0);
    lv_obj_set_align(ui_RedArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RedArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_RedArc, 0, 4200);
    lv_arc_set_value(ui_RedArc, 0);
    lv_arc_set_bg_angles(ui_RedArc, 90, 340);
    lv_obj_set_style_bg_color(ui_RedArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RedArc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RedArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RedArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RedArc, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedArc, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RedArc, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RedArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RedArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RedArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_RedArc, &ui_img_1798728470, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RedArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_StartButton = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_StartButton, 100);
    lv_obj_set_height(ui_StartButton, 50);
    lv_obj_set_x(ui_StartButton, 14);
    lv_obj_set_y(ui_StartButton, 114);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartButton, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunLabel = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_RunLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunLabel, "Run");
    lv_obj_set_style_text_color(ui_RunLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunLabel, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RunLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_StopButton, 100);
    lv_obj_set_height(ui_StopButton, 50);
    lv_obj_set_x(ui_StopButton, 131);
    lv_obj_set_y(ui_StopButton, 113);
    lv_obj_set_align(ui_StopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopButton, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StopButton, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StopButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLabel = lv_label_create(ui_StopButton);
    lv_obj_set_width(ui_StopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLabel, "E-Stop");
    lv_obj_set_style_text_color(ui_StopLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopLabel, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StopLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMPanel = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_RPMPanel, 100);
    lv_obj_set_height(ui_RPMPanel, 50);
    lv_obj_set_x(ui_RPMPanel, -173);
    lv_obj_set_y(ui_RPMPanel, 32);
    lv_obj_set_align(ui_RPMPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_RPMPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RPMPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_RPMPanel);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 29);
    lv_obj_set_y(ui_Label6, 13);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Rpm");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x80FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMLabel = lv_label_create(ui_RPMPanel);
    lv_obj_set_width(ui_RPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLabel, -8);
    lv_obj_set_y(ui_RPMLabel, -19);
    lv_label_set_text(ui_RPMLabel, "0000");
    lv_obj_set_style_text_color(ui_RPMLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMLabel, &ui_font_Font_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunMotorProfilePanel = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_RunMotorProfilePanel, 177);
    lv_obj_set_height(ui_RunMotorProfilePanel, 50);
    lv_obj_set_x(ui_RunMotorProfilePanel, -141);
    lv_obj_set_y(ui_RunMotorProfilePanel, 113);
    lv_obj_set_align(ui_RunMotorProfilePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RunMotorProfilePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_RunMotorProfilePanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RunMotorProfilePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunMotorProfileLabel = lv_label_create(ui_RunMotorProfilePanel);
    lv_obj_set_width(ui_RunMotorProfileLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunMotorProfileLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunMotorProfileLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunMotorProfileLabel, "Profile Selected:");
    lv_obj_set_style_text_color(ui_RunMotorProfileLabel, lv_color_hex(0x80FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunMotorProfileLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunMotorProfileLabel, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner3 = lv_spinner_create(ui_Screen4, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 40);
    lv_obj_set_height(ui_Spinner3, 40);
    lv_obj_set_x(ui_Spinner3, 208);
    lv_obj_set_y(ui_Spinner3, 112);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner3, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ToMainMenuPanel1, ui_event_ToMainMenuPanel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ToMainMenuPanel2, ui_event_ToMainMenuPanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton, ui_event_StopButton, LV_EVENT_ALL, NULL);

}
