// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeScreenPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_HomeScreenPanel, 480);
    lv_obj_set_height(ui_HomeScreenPanel, 320);
    lv_obj_set_align(ui_HomeScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeScreenBG = lv_img_create(ui_HomeScreenPanel);
    lv_img_set_src(ui_HomeScreenBG, &ui_img_789391261);
    lv_obj_set_width(ui_HomeScreenBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeScreenBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeScreenBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeScreenBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeScreenBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreenBG, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreenBG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_HomeScreenPanel);
    lv_obj_set_width(ui_TopPanel, 200);
    lv_obj_set_height(ui_TopPanel, 40);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -22);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeTopPanelLabel = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_HomeTopPanelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeTopPanelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeTopPanelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeTopPanelLabel, "SRG DMF Spin Coater");
    lv_obj_set_style_text_color(ui_HomeTopPanelLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeTopPanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeTopPanelLabel, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedBG = lv_img_create(ui_HomeScreenPanel);
    lv_img_set_src(ui_SpeedBG, &ui_img_speedbg_png);
    lv_obj_set_width(ui_SpeedBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedBG, 11);
    lv_obj_set_y(ui_SpeedBG, 101);
    lv_obj_set_align(ui_SpeedBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeedBG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeedBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_SpeedBG);
    lv_slider_set_range(ui_Slider2, 0, 3200);
    lv_slider_set_value(ui_Slider2, 2000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 120);
    lv_obj_set_height(ui_Slider2, 53);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_speedfg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MotorRPMPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MotorRPMPanel, 100);
    lv_obj_set_height(ui_MotorRPMPanel, 20);
    lv_obj_set_x(ui_MotorRPMPanel, 20);
    lv_obj_set_y(ui_MotorRPMPanel, 19);
    lv_obj_set_align(ui_MotorRPMPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorRPMPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MotorRPMPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorRPMPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorRPMPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorRPMPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorRPMPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorRPMPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorMaxRPM = lv_label_create(ui_MotorRPMPanel);
    lv_obj_set_width(ui_MotorMaxRPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorMaxRPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MotorMaxRPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorMaxRPM, "Motor RPM");
    lv_obj_add_flag(ui_MotorMaxRPM, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_MotorMaxRPM, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorMaxRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorMaxRPM, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedIndicatorPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedIndicatorPanel, 84);
    lv_obj_set_height(ui_SpeedIndicatorPanel, 45);
    lv_obj_set_x(ui_SpeedIndicatorPanel, 33);
    lv_obj_set_y(ui_SpeedIndicatorPanel, 105);
    lv_obj_set_align(ui_SpeedIndicatorPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SpeedIndicatorPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SpeedIndicatorPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_SpeedIndicatorPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpeedIndicatorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SpeedIndicatorPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedIndicatorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedIndicatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedIndicatorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorRpm = lv_label_create(ui_SpeedIndicatorPanel);
    lv_obj_set_width(ui_MotorRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorRpm, -11);
    lv_obj_set_y(ui_MotorRpm, -91);
    lv_obj_set_align(ui_MotorRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorRpm, "0000");
    lv_obj_set_style_text_color(ui_MotorRpm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorRpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorRpm, &ui_font_Font_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status_Panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Status_Panel, 350);
    lv_obj_set_height(ui_Status_Panel, 60);
    lv_obj_set_x(ui_Status_Panel, 1);
    lv_obj_set_y(ui_Status_Panel, -51);
    lv_obj_set_align(ui_Status_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Status_Panel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Status_Panel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Status_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Status_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Status_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Status_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Status_Panel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel = lv_label_create(ui_Status_Panel);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel, -16);
    lv_obj_set_y(ui_StatusLabel, -37);
    lv_label_set_text(ui_StatusLabel, "Motor Ready: ");
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OperationMode = lv_label_create(ui_Status_Panel);
    lv_obj_set_width(ui_OperationMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperationMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperationMode, -15);
    lv_obj_set_y(ui_OperationMode, 4);
    lv_obj_set_align(ui_OperationMode, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_OperationMode, "Selected Profile:");
    lv_obj_set_style_text_color(ui_OperationMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OperationMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OperationMode, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorStatus = lv_label_create(ui_Status_Panel);
    lv_obj_set_width(ui_MotorStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorStatus, -339);
    lv_obj_set_y(ui_MotorStatus, 115);
    lv_label_set_text(ui_MotorStatus, "Not Connected");
    lv_obj_set_style_text_color(ui_MotorStatus, lv_color_hex(0x940000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorStatus, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectedProfileNumber1 = lv_label_create(ui_Status_Panel);
    lv_obj_set_width(ui_SelectedProfileNumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectedProfileNumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectedProfileNumber1, -339);
    lv_obj_set_y(ui_SelectedProfileNumber1, 115);
    lv_label_set_text(ui_SelectedProfileNumber1, "Spin Profile 3");
    lv_obj_set_style_text_color(ui_SelectedProfileNumber1, lv_color_hex(0x004204), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelectedProfileNumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectedProfileNumber1, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner, 30);
    lv_obj_set_height(ui_Spinner, 30);
    lv_obj_set_x(ui_Spinner, 190);
    lv_obj_set_y(ui_Spinner, -139);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SettingPanels = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SettingPanels, 69);
    lv_obj_set_height(ui_SettingPanels, 87);
    lv_obj_set_x(ui_SettingPanels, 162);
    lv_obj_set_y(ui_SettingPanels, 106);
    lv_obj_set_align(ui_SettingPanels, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingPanels, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingPanels, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPanels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingPanels, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingPanels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingPageLabel = lv_label_create(ui_SettingPanels);
    lv_obj_set_width(ui_SettingPageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingPageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingPageLabel, -1);
    lv_obj_set_y(ui_SettingPageLabel, -2);
    lv_obj_set_align(ui_SettingPageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingPageLabel, "Profiles");
    lv_obj_add_flag(ui_SettingPageLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SettingPageLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingPageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingPageLabel, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectedProfile = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_SelectedProfile, 122);
    lv_obj_set_height(ui_SelectedProfile, 67);
    lv_obj_set_x(ui_SelectedProfile, 23);
    lv_obj_set_y(ui_SelectedProfile, 232);
    lv_obj_set_align(ui_SelectedProfile, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_SelectedProfile, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_chart_set_type(ui_SelectedProfile, LV_CHART_TYPE_SCATTER);
    lv_chart_set_range(ui_SelectedProfile, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_SelectedProfile, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_SelectedProfile, 10, 10);
    lv_chart_set_axis_tick(ui_SelectedProfile, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, false, 50);
    lv_chart_set_axis_tick(ui_SelectedProfile, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_SelectedProfile, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_StartPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_StartPanel, 119);
    lv_obj_set_height(ui_StartPanel, 87);
    lv_obj_set_x(ui_StartPanel, -138);
    lv_obj_set_y(ui_StartPanel, 107);
    lv_obj_set_align(ui_StartPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StartPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StartPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_StartPanel);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartLabel, -1);
    lv_obj_set_y(ui_StartLabel, -2);
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "Start \nSelection");
    lv_obj_add_flag(ui_StartLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_StartLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartLabel, &ui_font_Font_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingPageLabel, ui_event_SettingPageLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingPanels, ui_event_SettingPanels, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartLabel, ui_event_StartLabel, LV_EVENT_ALL, NULL);

}
