// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Needle_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_HomeScreenPanel;
lv_obj_t * ui_HomeScreenBG;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_HomeTopPanelLabel;
lv_obj_t * ui_SpeedBG;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_MotorRPMPanel;
lv_obj_t * ui_MotorMaxRPM;
lv_obj_t * ui_SpeedIndicatorPanel;
lv_obj_t * ui_MotorRpm;
lv_obj_t * ui_Status_Panel;
lv_obj_t * ui_StatusLabel;
lv_obj_t * ui_OperationMode;
lv_obj_t * ui_MotorStatus;
lv_obj_t * ui_SelectedProfileNumber1;
lv_obj_t * ui_Spinner;
void ui_event_SettingPanels(lv_event_t * e);
lv_obj_t * ui_SettingPanels;
void ui_event_SettingPageLabel(lv_event_t * e);
lv_obj_t * ui_SettingPageLabel;
lv_obj_t * ui_SelectedProfile;
lv_obj_t * ui_StartPanel;
void ui_event_StartLabel(lv_event_t * e);
lv_obj_t * ui_StartLabel;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_SettingScreenPanel;
lv_obj_t * ui_TopPanelSetting;
lv_obj_t * ui_SettingTopPanelLabel1;
void ui_event_ToMainMenuPanel(lv_event_t * e);
lv_obj_t * ui_ToMainMenuPanel;
lv_obj_t * ui_ToMainMenuLabel;
void ui_event_ProfilePanel1(lv_event_t * e);
lv_obj_t * ui_ProfilePanel1;
lv_obj_t * ui_Profile1;
lv_obj_t * ui_ProfileLabel1;
void ui_event_ProfilePanel2(lv_event_t * e);
lv_obj_t * ui_ProfilePanel2;
lv_obj_t * ui_Profile2;
lv_obj_t * ui_ProfileLabel2;
void ui_event_ProfilePanel3(lv_event_t * e);
lv_obj_t * ui_ProfilePanel3;
lv_obj_t * ui_Profile3;
lv_obj_t * ui_ProfileLabel3;
void ui_event_ProfilePanel4(lv_event_t * e);
lv_obj_t * ui_ProfilePanel4;
lv_obj_t * ui_Profile4;
lv_obj_t * ui_ProfileLabel4;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_EditProfileScreenPanel1;
lv_obj_t * ui_EditProfileTopPanel1;
lv_obj_t * ui_EditProfileTopLabel;
void ui_event_EditProfileBackPanel(lv_event_t * e);
lv_obj_t * ui_EditProfileBackPanel;
lv_obj_t * ui_EditProfileBackLabel;
void ui_event_EditProfileSelectPanel(lv_event_t * e);
lv_obj_t * ui_EditProfileSelectPanel;
lv_obj_t * ui_EditProfileSelectLabel;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_PanelForParams;
lv_obj_t * ui_TimeLabel1;
void ui_event_Time1(lv_event_t * e);
lv_obj_t * ui_Time1;
lv_obj_t * ui_RPMLabel1;
void ui_event_RPM1(lv_event_t * e);
lv_obj_t * ui_RPM1;
lv_obj_t * ui_TimeLabel2;
void ui_event_Time2(lv_event_t * e);
lv_obj_t * ui_Time2;
lv_obj_t * ui_RPMLabel2;
void ui_event_RPM2(lv_event_t * e);
lv_obj_t * ui_RPM2;
lv_obj_t * ui_TimeLabel3;
void ui_event_Time3(lv_event_t * e);
lv_obj_t * ui_Time3;
lv_obj_t * ui_RPMLabel3;
void ui_event_RPM3(lv_event_t * e);
lv_obj_t * ui_RPM3;
lv_obj_t * ui_TimeLabel4;
void ui_event_Time4(lv_event_t * e);
lv_obj_t * ui_Time4;
lv_obj_t * ui_RPMLabel4;
void ui_event_RPM4(lv_event_t * e);
lv_obj_t * ui_RPM4;
lv_obj_t * ui_TimeLabel5;
void ui_event_Time5(lv_event_t * e);
lv_obj_t * ui_Time5;
lv_obj_t * ui_RPMLabel5;
void ui_event_RPM5(lv_event_t * e);
lv_obj_t * ui_RPM5;
lv_obj_t * ui_TimeLabel6;
void ui_event_Time6(lv_event_t * e);
lv_obj_t * ui_Time6;
lv_obj_t * ui_RPMLabel6;
void ui_event_RPM6(lv_event_t * e);
lv_obj_t * ui_RPM6;
lv_obj_t * ui_TimeLabel7;
void ui_event_Time7(lv_event_t * e);
lv_obj_t * ui_Time7;
lv_obj_t * ui_RPMLabel7;
void ui_event_RPM7(lv_event_t * e);
lv_obj_t * ui_RPM7;
lv_obj_t * ui_TimeLabel8;
void ui_event_Time8(lv_event_t * e);
lv_obj_t * ui_Time8;
lv_obj_t * ui_RPMLabel8;
void ui_event_RPM8(lv_event_t * e);
lv_obj_t * ui_RPM8;
lv_obj_t * ui_TimeLabel9;
void ui_event_Time9(lv_event_t * e);
lv_obj_t * ui_Time9;
lv_obj_t * ui_RPMLabel9;
void ui_event_RPM9(lv_event_t * e);
lv_obj_t * ui_RPM9;
lv_obj_t * ui_TimeLabel10;
void ui_event_Time10(lv_event_t * e);
lv_obj_t * ui_Time10;
lv_obj_t * ui_RPMLabel10;
void ui_event_RPM10(lv_event_t * e);
lv_obj_t * ui_RPM10;
lv_obj_t * ui_EditProfile;
// CUSTOM VARIABLES
lv_obj_t * uic_Time1;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_SettingScreenPanel1;
lv_obj_t * ui_TopPanelStart;
lv_obj_t * ui_TopPanelStartLabel;
void ui_event_ToMainMenuPanel1(lv_event_t * e);
lv_obj_t * ui_ToMainMenuPanel1;
lv_obj_t * ui_ToMainMenuLabel1;
void ui_event_ToMainMenuPanel2(lv_event_t * e);
lv_obj_t * ui_ToMainMenuPanel2;
lv_obj_t * ui_ToMainMenuLabel2;
lv_obj_t * ui_RunningProfilePanel;
lv_obj_t * ui_RunningProfile;
lv_obj_t * ui_SpeedPanel;
lv_obj_t * ui_BGSpeed;
lv_obj_t * ui_Needle;
lv_obj_t * ui_RedArc;
void ui_event_StartButton(lv_event_t * e);
lv_obj_t * ui_StartButton;
lv_obj_t * ui_RunLabel;
void ui_event_StopButton(lv_event_t * e);
lv_obj_t * ui_StopButton;
lv_obj_t * ui_StopLabel;
lv_obj_t * ui_RPMPanel;
lv_obj_t * ui_Label6;
lv_obj_t * ui_RPMLabel;
lv_obj_t * ui_RunMotorProfilePanel;
lv_obj_t * ui_RunMotorProfileLabel;
lv_obj_t * ui_Spinner3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_ManualRunScreenPanel;
lv_obj_t * ui_ManualPanelTop;
lv_obj_t * ui_ManualRunLabel;
void ui_event_ToMainMenuPanel3(lv_event_t * e);
lv_obj_t * ui_ToMainMenuPanel3;
lv_obj_t * ui_ToMainMenuLabel3;
lv_obj_t * ui_SpeedPanel1;
lv_obj_t * ui_BGSpeed1;
lv_obj_t * ui_Needle1;
lv_obj_t * ui_Arc2;
void ui_event_StartManualButton(lv_event_t * e);
lv_obj_t * ui_StartManualButton;
lv_obj_t * ui_RunLabel1;
void ui_event_StopButton1(lv_event_t * e);
lv_obj_t * ui_StopButton1;
lv_obj_t * ui_StopLabel1;
lv_obj_t * ui_RPMPanel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_RPMLabel11;
void ui_event_RpmKnob(lv_event_t * e);
lv_obj_t * ui_RpmKnob;
lv_obj_t * ui_ManualMinRPM;
lv_obj_t * ui_ManualMaxRPM;
lv_obj_t * ui_ManualRPMLabel;
void ui_event_minus50Button(lv_event_t * e);
lv_obj_t * ui_minus50Button;
lv_obj_t * ui_minus50Label;
void ui_event_plus50Button(lv_event_t * e);
lv_obj_t * ui_plus50Button;
lv_obj_t * ui_plus50Label;
lv_obj_t * ui_Spinner4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1780164337[1] = {&ui_img_789391261};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Needle_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 5000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_SettingPanels(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setupProfileGraphs(e);
    }
}

void ui_event_SettingPageLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen2_screen_init);
        setupProfileGraphs(e);
    }
}

void ui_event_StartLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        setRunChart(e);
    }
}

void ui_event_ToMainMenuPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ProfilePanel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen3_screen_init);
        setProfileNumber(e);
        _ui_label_set_property(ui_EditProfileTopLabel, _UI_LABEL_PROPERTY_TEXT, "Profile 1");
    }
}

void ui_event_ProfilePanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setProfileNumber(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen3_screen_init);
        _ui_label_set_property(ui_EditProfileTopLabel, _UI_LABEL_PROPERTY_TEXT, "Profile 2");
    }
}

void ui_event_ProfilePanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setProfileNumber(e);
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen3_screen_init);
        _ui_label_set_property(ui_EditProfileTopLabel, _UI_LABEL_PROPERTY_TEXT, "Profile 3");
    }
}

void ui_event_ProfilePanel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen3_screen_init);
        setProfileNumber(e);
        _ui_label_set_property(ui_EditProfileTopLabel, _UI_LABEL_PROPERTY_TEXT, "Profile 4");
    }
}

void ui_event_EditProfileBackPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen2_screen_init);
        setupProfileGraphs(e);
    }
}

void ui_event_EditProfileSelectPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen1_screen_init);
        setSelectedMode(e);
    }
}

void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        KeyboardDone(e);
    }
}

void ui_event_Time1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time1);
    }
}

void ui_event_RPM1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM1);
    }
}

void ui_event_Time2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time2);
    }
}

void ui_event_RPM2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM2);
    }
}

void ui_event_Time3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time3);
    }
}

void ui_event_RPM3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM3);
    }
}

void ui_event_Time4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time4);
    }
}

void ui_event_RPM4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM4);
    }
}

void ui_event_Time5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time5);
    }
}

void ui_event_RPM5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM5);
    }
}

void ui_event_Time6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time6);
    }
}

void ui_event_RPM6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM6);
    }
}

void ui_event_Time7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time7);
    }
}

void ui_event_RPM7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM7);
    }
}

void ui_event_Time8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time8);
    }
}

void ui_event_RPM8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM8);
    }
}

void ui_event_Time9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time9);
    }
}

void ui_event_RPM9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM9);
    }
}

void ui_event_Time10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_Time10);
    }
}

void ui_event_RPM10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_RPM10);
    }
}

void ui_event_ToMainMenuPanel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ToMainMenuPanel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_StartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        runButtonTriggered(e);
    }
}

void ui_event_StopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StopButtonTriggered(e);
    }
}

void ui_event_ToMainMenuPanel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_StartManualButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        runManualButtonTriggered(e);
    }
}

void ui_event_StopButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StopButtonTriggered(e);
    }
}

void ui_event_RpmKnob(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetRpmSlider(e);
    }
}

void ui_event_minus50Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        minus50RPM(e);
        (e);
    }
}

void ui_event_plus50Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        add50RPM(e);
        (e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
