// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingScreenPanel = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SettingScreenPanel, 480);
    lv_obj_set_height(ui_SettingScreenPanel, 320);
    lv_obj_set_align(ui_SettingScreenPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanelSetting = lv_obj_create(ui_SettingScreenPanel);
    lv_obj_set_width(ui_TopPanelSetting, 200);
    lv_obj_set_height(ui_TopPanelSetting, 40);
    lv_obj_set_x(ui_TopPanelSetting, 0);
    lv_obj_set_y(ui_TopPanelSetting, -22);
    lv_obj_set_align(ui_TopPanelSetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TopPanelSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TopPanelSetting, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TopPanelSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingTopPanelLabel1 = lv_label_create(ui_TopPanelSetting);
    lv_obj_set_width(ui_SettingTopPanelLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingTopPanelLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingTopPanelLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingTopPanelLabel1, "Profiles");
    lv_obj_set_style_text_color(ui_SettingTopPanelLabel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingTopPanelLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingTopPanelLabel1, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuPanel = lv_obj_create(ui_SettingScreenPanel);
    lv_obj_set_width(ui_ToMainMenuPanel, 98);
    lv_obj_set_height(ui_ToMainMenuPanel, 40);
    lv_obj_set_x(ui_ToMainMenuPanel, -186);
    lv_obj_set_y(ui_ToMainMenuPanel, -23);
    lv_obj_set_align(ui_ToMainMenuPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ToMainMenuPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ToMainMenuPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ToMainMenuPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ToMainMenuLabel = lv_label_create(ui_ToMainMenuPanel);
    lv_obj_set_width(ui_ToMainMenuLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToMainMenuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToMainMenuLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ToMainMenuLabel, "< Main");
    lv_obj_set_style_text_color(ui_ToMainMenuLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ToMainMenuLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ToMainMenuLabel, &ui_font_Display_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePanel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ProfilePanel1, 228);
    lv_obj_set_height(ui_ProfilePanel1, 120);
    lv_obj_set_x(ui_ProfilePanel1, -118);
    lv_obj_set_y(ui_ProfilePanel1, -45);
    lv_obj_set_align(ui_ProfilePanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProfilePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Profile1 = lv_chart_create(ui_ProfilePanel1);
    lv_obj_set_width(ui_Profile1, 180);
    lv_obj_set_height(ui_Profile1, 80);
    lv_obj_set_x(ui_Profile1, 19);
    lv_obj_set_y(ui_Profile1, -11);
    lv_obj_set_align(ui_Profile1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Profile1, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Profile1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_Profile1, LV_CHART_TYPE_SCATTER);
    lv_chart_set_range(ui_Profile1, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_Profile1, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_Profile1, 10, 10);
    lv_chart_set_axis_tick(ui_Profile1, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Profile1, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Profile1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_ProfileLabel1 = lv_label_create(ui_ProfilePanel1);
    lv_obj_set_width(ui_ProfileLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileLabel1, 4);
    lv_obj_set_y(ui_ProfileLabel1, 52);
    lv_obj_set_align(ui_ProfileLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileLabel1, "Edit Profile 1");
    lv_obj_set_style_text_color(ui_ProfileLabel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfileLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileLabel1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePanel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ProfilePanel2, 228);
    lv_obj_set_height(ui_ProfilePanel2, 120);
    lv_obj_set_x(ui_ProfilePanel2, 118);
    lv_obj_set_y(ui_ProfilePanel2, -45);
    lv_obj_set_align(ui_ProfilePanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProfilePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Profile2 = lv_chart_create(ui_ProfilePanel2);
    lv_obj_set_width(ui_Profile2, 180);
    lv_obj_set_height(ui_Profile2, 80);
    lv_obj_set_x(ui_Profile2, 19);
    lv_obj_set_y(ui_Profile2, -11);
    lv_obj_set_align(ui_Profile2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Profile2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Profile2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_Profile2, LV_CHART_TYPE_SCATTER);
    lv_chart_set_range(ui_Profile2, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_Profile2, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_Profile2, 10, 10);
    lv_chart_set_axis_tick(ui_Profile2, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Profile2, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Profile2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_ProfileLabel2 = lv_label_create(ui_ProfilePanel2);
    lv_obj_set_width(ui_ProfileLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileLabel2, 4);
    lv_obj_set_y(ui_ProfileLabel2, 52);
    lv_obj_set_align(ui_ProfileLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileLabel2, "Edit Profile 2");
    lv_obj_set_style_text_color(ui_ProfileLabel2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfileLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileLabel2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePanel3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ProfilePanel3, 228);
    lv_obj_set_height(ui_ProfilePanel3, 120);
    lv_obj_set_x(ui_ProfilePanel3, -117);
    lv_obj_set_y(ui_ProfilePanel3, 84);
    lv_obj_set_align(ui_ProfilePanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProfilePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Profile3 = lv_chart_create(ui_ProfilePanel3);
    lv_obj_set_width(ui_Profile3, 180);
    lv_obj_set_height(ui_Profile3, 80);
    lv_obj_set_x(ui_Profile3, 19);
    lv_obj_set_y(ui_Profile3, -11);
    lv_obj_set_align(ui_Profile3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Profile3, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Profile3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_Profile3, LV_CHART_TYPE_SCATTER);
    lv_chart_set_range(ui_Profile3, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_Profile3, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_Profile3, 10, 10);
    lv_chart_set_axis_tick(ui_Profile3, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Profile3, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Profile3, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_ProfileLabel3 = lv_label_create(ui_ProfilePanel3);
    lv_obj_set_width(ui_ProfileLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileLabel3, 4);
    lv_obj_set_y(ui_ProfileLabel3, 52);
    lv_obj_set_align(ui_ProfileLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileLabel3, "Edit Profile 3");
    lv_obj_set_style_text_color(ui_ProfileLabel3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfileLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileLabel3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProfilePanel4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_ProfilePanel4, 228);
    lv_obj_set_height(ui_ProfilePanel4, 120);
    lv_obj_set_x(ui_ProfilePanel4, 119);
    lv_obj_set_y(ui_ProfilePanel4, 84);
    lv_obj_set_align(ui_ProfilePanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProfilePanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Profile4 = lv_chart_create(ui_ProfilePanel4);
    lv_obj_set_width(ui_Profile4, 180);
    lv_obj_set_height(ui_Profile4, 80);
    lv_obj_set_x(ui_Profile4, 19);
    lv_obj_set_y(ui_Profile4, -11);
    lv_obj_set_align(ui_Profile4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Profile4, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Profile4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_chart_set_type(ui_Profile4, LV_CHART_TYPE_SCATTER);
    lv_chart_set_range(ui_Profile4, LV_CHART_AXIS_PRIMARY_Y, 0, 4000);
    lv_chart_set_range(ui_Profile4, LV_CHART_AXIS_SECONDARY_Y, 0, 300);
    lv_chart_set_div_line_count(ui_Profile4, 10, 10);
    lv_chart_set_axis_tick(ui_Profile4, LV_CHART_AXIS_PRIMARY_X, 0, 1, 10, 1, true, 50);
    lv_chart_set_axis_tick(ui_Profile4, LV_CHART_AXIS_PRIMARY_Y, 0, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Profile4, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);



    ui_ProfileLabel4 = lv_label_create(ui_ProfilePanel4);
    lv_obj_set_width(ui_ProfileLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileLabel4, 4);
    lv_obj_set_y(ui_ProfileLabel4, 52);
    lv_obj_set_align(ui_ProfileLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProfileLabel4, "Edit Profile 4");
    lv_obj_set_style_text_color(ui_ProfileLabel4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProfileLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProfileLabel4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ToMainMenuPanel, ui_event_ToMainMenuPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePanel1, ui_event_ProfilePanel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePanel2, ui_event_ProfilePanel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePanel3, ui_event_ProfilePanel3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProfilePanel4, ui_event_ProfilePanel4, LV_EVENT_ALL, NULL);

}
